### ISSUE TITLE
'Discover' object has no attribute 'dens_score_df'

### ISSUE THREAD

**Issue by ancarnevali** [sparks-baird/mat_discover#55]
Hi!
I'd like to open a fitted model in order to elaborate on its clusters, and found the `disc.load()` method. 
I load the method with 
```
>> disc=Discover()
>>> disc.load(fpath='C:/Users/anton/OneDrive/Desktop/matdisc_colab/formula_discharge vs capacity_grav/disc.pkl')
<mat_discover.mat_discover_.Discover object at 0x0000015006F56D90>
```
but, when trying to use some methods like `disc.merge()` or `disc.cluster_avg()` it appears that the Discover() object lacks attributes. 
Some examples:
```
>>> disc.cluster_avg()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Discover' object has no attribute 'cluster_avg'
```
```
>>> disc.merge()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\anton\miniconda3\envs\matdisc\lib\site-packages\mat_discover\mat_discover_.py", line 848, in merge
    dens_score_df = self.dens_score_df.rename(columns={"score": "Density Score"})
AttributeError: 'Discover' object has no attribute 'dens_score_df'
```
```
>>> disc.compute_log_density()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\anton\miniconda3\envs\matdisc\lib\site-packages\mat_discover\mat_discover_.py", line 1261, in compute_log_density
    r_orig = self.std_r_orig
AttributeError: 'Discover' object has no attribute 'std_r_orig'
```
The folder where `disc.pkl` is stored contains the three folders "figures", "models", "tables", and `disk.pkl` itself. The same occurs for other folders structured similarly.
Am I doing something wrong here or is there a possible bug in the `load()` method?

**Comment by sgbaird** [comment]
Note that some of the attributes are assigned during predict, and in the current implementation, `mat_discover` can't be used on new data due to use of "precomputed" distance matrices calculated during `predict`. This hasn't been a major hindrance for me since it runs fairly quickly on a GPU, and even a CPU for moderate-sized dataset (e.g. 10k points). This is on my to-do list, so if it's a major setback for you I can take another stab sooner.

**Comment by sgbaird** [comment]
Did you run `disc.predict` before doing this?

**Comment by ancarnevali** [comment]
ok that was pretty dumb on my side, I didn't define the loaded model like `d = disc.load(path)`. Doing this loads the indicated model, and the methods I mentioned above work with the exception of `cluster_avg`, that gives `[TypeError: 'numpy.ndarray' object is not callable]()`. Running `disc.predict` doesn't seem to affect the `load` method.

Interestingly though, if I try to load a model I fitted on Google Colab, the loading doesn't always work. Most of the times it returns `[ModuleNotFoundError: No module named 'crabnet.model']()`, even though I download the disc.pkl file as it is from the Colab folder through Drive. I'll try to get some more information about this problem.

**Comment by sgbaird** [comment]
> ok that was pretty dumb on my side, I didn't define the loaded model like `d = disc.load(path)`. Doing this loads the indicated model, and the methods I mentioned above work with the exception of `cluster_avg`, that gives `[TypeError: 'numpy.ndarray' object is not callable]()`. Running `disc.predict` doesn't seem to affect the `load` method.

No worries. Ok, yeah I'll need to check into why that is for `cluster_avg`.

> Interestingly though, if I try to load a model I fitted on Google Colab, the loading doesn't always work. Most of the times it returns `[ModuleNotFoundError: No module named 'crabnet.model']()`, even though I download the disc.pkl file as it is from the Colab folder through Drive. I'll try to get some more information about this problem. 

I ran into this issue before and couldn't figure it out at the time, so I opened it in a separate GitHub issue before.

**Comment by sgbaird** [comment]
#39

**Comment by sgbaird** [comment]
@ancarnevali The issue is probably a difference in `mat_discover` versions. When I bumped from version 1 to version 2, I replaced `crabnet.model` with `crabnet.crabnet_` and got rid of `train_crabnet.py`. This was part of a series of changes I've been wanting to make for a long time. If you install e.g. `1.3.1` I think you will be able to load the models you fitted before. `pickle` is easy, but maintaining `load` and `save` version compatibility when breaking changes occur can be tough (maybe there's an easier way I'm not aware of). Let me know if there's anything you need on this front.

**Comment by sgbaird** [comment]
Btw, I checked back into `cluster_avg` and it looks like it's not a method, but an array that only gets assigned under certain conditions.

https://github.com/sparks-baird/mat_discover/blob/025ac8a862e5da5c6b8ce3bd87d89c612562572e/mat_discover/mat_discover_.py#L634-L639
